# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 543e4789b52a1f24d580668e6ec78544e5de8d202e4c6db6dc32eb3a18a6349bb832d4e800771968ff6ab3f7a3a3aa432628c9d76f9e344c97b49605683f6f59

test:
  secret_key_base: 39ac9e2cd7a6df0aebcee2c67b484b8865dac15d424db9d47e2e38b9e2c10bae50661a2231df7eb9399da74f9f7ea7019381a2101f45deebe7de9191051f5155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
